---
- name: Add containerd repository
  ansible.builtin.copy:
    dest: /etc/yum.repos.d/docker-ce.repo
    content: |
      [docker-ce-stable]
      name=Docker CE Stable - $basearch
      baseurl=https://download.docker.com/linux/centos/$releasever/$basearch/stable
      enabled=1
      gpgcheck=1
      gpgkey=https://download.docker.com/linux/centos/gpg

- name: Install containerd
  ansible.builtin.package:
    name: containerd.io
    state: present
  notify: Restart containerd

- name: Backup and replace containerd configuration
  ansible.builtin.copy:
    src: /etc/containerd/config.toml
    dest: /etc/containerd/config.toml.bak
    remote_src: true
  ignore_errors: true

- name: Replace containerd configuration with new configuration
  ansible.builtin.copy:
    dest: /etc/containerd/config.toml
    content: |
      version = 2
      disabled_plugins = []

      [plugins."io.containerd.grpc.v1.cri"]
        sandbox_image = "registry.k8s.io/pause:3.9"
      [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc]
        runtime_type = "io.containerd.runc.v2"
        [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc.options]
          SystemdCgroup = true
  notify: Restart containerd

- name: Ensure correct permissions on containerd socket directory
  ansible.builtin.file:
    path: /run/containerd
    state: directory
    mode: '0755'
    owner: root
    group: root

- name: Start and enable containerd service
  ansible.builtin.service:
    name: containerd
    state: started
    enabled: true
