---
- name: Create a kube repo file
  ansible.builtin.file:
   path: "/etc/yum.repos.d/kubernetes.repo"
   state: "touch"

- name: write repo information in kube repo file
  blockinfile:
   path: "/etc/yum.repos.d/kubernetes.repo"
   block: |
          [kubernetes]
          name=Kubernetes
          baseurl={{ kubernetes_repo_url }}
          enabled=1
          gpgcheck=1
          repo_gpgcheck=1
          gpgkey={{ kubernetes_gpg_key }}
- name: Install kubernetes packages
  ansible.builtin.package:
   name:
     - kubelet-{{ kubernetes_version }}
     - kubeadm-{{ kubernetes_version }}
     - kubectl-{{ kubernetes_version }}
   state: present

- name: Enable kubelet service
  ansible.builtin.systemd:
    name: kubelet
    enabled: true
