# defaults/main.yml
# 1. Repository configuration
fix_debian_sources: true
disable_enterprise_repo: true
enable_no_subscription_repo: true
add_test_repo: true
disable_subscription_nag: true
do_update: true
do_reboot: false

# 2. VirtIO drivers
virtio_iso_path: "/var/lib/vz/template/iso"
virtio_download_url: "https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/latest-virtio/virtio-win.iso"

# 3. Networking variables
network_bridges:
      - name: vmbr0
        interface: enp5s0
        address: 192.168.1.3
        netmask: 255.255.255.0
        gateway: 192.168.1.1
        comments: "Management Network and VM Network"
      - name: vmbr1
        interface: enp6s0
        address: 10.10.10.1
        netmask: 255.255.255.0
        gateway: ""
        comments: "Private Network for VMs"
      - name: vmbr2
        interface: enp7s0
        address: 192.168.2.10
        netmask: 255.255.255.0
        gateway: ""
        comments: "Dedicated NFS Traffic Network"



confirm_wipe: 'yes'
zfs_pool_name: shared_pool
disks:
  - '/dev/sdb'
  - '/dev/sdc'
datasets:
  - name: "k8s_volumes"
    extra_zfs_properties:
      quota: '1.5T'
      compression: 'lz4'
      recordsize: '128K'
      sync: 'standard'
  - name: "monitoring"
    extra_zfs_properties:
      quota: '600G'
      compression: 'lz4'
      recordsize: '256K'
      sync: 'disabled'
  - name: "other"
    extra_zfs_properties:
      quota: '500G'
      compression: 'lz4'
      recordsize: '128K'
      sync: 'standard'
  - name: "samba_share"
    extra_zfs_properties:
      quota: '300G'
      compression: 'lz4'
      recordsize: '1M'
      sync: 'standard'


# 5. GPU passthrough + IOMMU
grub_file: "/etc/default/grub"
modules_file: "/etc/modules"
blacklist_file: "/etc/modprobe.d/blacklist.conf"
iommu_file: "/etc/modprobe.d/iommu_unsafe_interrupts.conf"
vfio_file: "/etc/modprobe.d/vfio.conf"
kvm_file: "/etc/modprobe.d/kvm.conf"

# We'll gather CPU data from ansible_facts['ansible_processor'] in tasks
cpu_vendor: ""  # or set a fallback string like "GenuineIntel" or "AuthenticAMD"