---
- name: Add HashiCorp repository
  ansible.builtin.yum_repository:
    name: hashicorp
    description: HashiCorp Stable - $basearch
    baseurl: https://rpm.releases.hashicorp.com/RHEL/$releasever/$basearch/stable
    gpgkey: https://rpm.releases.hashicorp.com/gpg
    gpgcheck: true

- name: Install Vault
  ansible.builtin.package:
    name: vault
    state: present

- name: Create data directory
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: vault
    group: vault
    mode: '0750'
  loop:
    - "{{ vault_storage_path }}"
    - /etc/vault.d/tls
    - /etc/vault.d/k8s

- name: Configure Vault
  ansible.builtin.template:
    src: templates/vault.hcl.j2
    dest: /etc/vault.d/vault.hcl
    owner: vault
    group: vault
    mode: '0640'
  notify: Restart vault

- name: Open vault ports
  ansible.builtin.firewalld:
    port: "{{ item }}"
    permanet: true
    state: enabled
  loop:
    - 8200/tcp
    - 8201/tcp
  notify: Reload firewall

- name: Start and enable Vault
  ansible.builtin.systemd:
    name: vault
    state: started
    enabled: true
