---
- name: Join additional master nodes
  ansible.builtin.command:
    cmd: "{{ hostvars[groups['prod_control_plane'][0]]['cp_join_cmd'].stdout }} \
          --control-plane \
          --certificate-key {{ hostvars[groups['prod_control_plane'][0]]['certificate_key'] }} \
          --apiserver-advertise-address={{ ansible_host }}"
  changed_when: false
  when:
    - inventory_hostname in groups['prod_control_plane']
    - inventory_hostname != groups['prod_control_plane'][0]

- name: Join worker nodes to cluster
  ansible.builtin.command:
    cmd: "{{ hostvars[groups['prod_control_plane'][0]]['worker_join_cmd'].stdout }}"
  changed_when: false
  when: inventory_hostname in groups['prod_workers']