---
- name: Disable swap temporarily
  ansible.builtin.command:
    cmd: "swapoff -a"
  register: swapoff_result
  changed_when: swapoff_result.rc == 0

- name: Disable swap permanently in fstab
  ansible.builtin.lineinfile:
    path: /etc/fstab
    regexp: '\s+swap\s+'
    state: absent

- name: Check if br_netfilter module is loaded
  ansible.builtin.shell:
    cmd: "lsmod | grep br_netfilter"
  register: br_netfilter_check
  changed_when: false
  failed_when: false

- name: Load br_netfilter kernel module
  community.general.modprobe:
    name: br_netfilter
    state: present
  when: br_netfilter_check.rc != 0

- name: Get current sysctl values
  ansible.builtin.command:
    cmd: sysctl -n {{ item }}
  loop:
    - net.bridge.bridge-nf-call-iptables
    - net.ipv4.ip_forward
  register: sysctl_values
  changed_when: false

- name: Set bridge-nf-call-iptables
  ansible.posix.sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: '1'
    state: present
  when: sysctl_values.results[0].stdout != "1"

- name: Set ip_forward
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    state: present
  when: sysctl_values.results[1].stdout != "1"

- name: Create an empty file for K8S sysctl parameters
  ansible.builtin.copy:
    content: ""
    dest: /etc/sysctl.d/99-kubernetes-cri.conf
    force: false
    mode: '0644'

- name: Configure sysctl parameters for K8S
  ansible.builtin.lineinfile:
    path: /etc/sysctl.d/99-kubernetes-cri.conf
    line: "{{ item }}"
    mode: '0644'
  with_items:
    - "net.bridge.bridge-nf-call-iptables  = 1"
    - "net.ipv4.ip_forward                 = 1"
    - "net.bridge.bridge-nf-call-ip6tables = 1"

- name: Configure firewall for Control Plane nodes
  ansible.posix.firewalld:
    port: "{{ item }}"
    permanent: true
    state: enabled
  loop:
    - 6443/tcp
    - 2379-2380/tcp
    - 10250/tcp
    - 10259/tcp
    - 10257/tcp
  when: inventory_hostname in groups['prod_control_plane'] 
  notify: Reload firewall

- name: Configure firewall for Worker nodes
  ansible.posix.firewalld:
    port: "{{ item }}"
    permanent: true
    state: enabled
  loop:
    - 10250/tcp
    - 30000-32767/tcp
  when: inventory_hostname in groups['prod_workers'] 
  notify: Reload firewall
  

- name: Force handlers to run now
  meta: flush_handlers